/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2023-12-14 07:16:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.util.BSPageBar;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/include/gym_footer.jsp", Long.valueOf(1701408962000L));
    _jspx_dependants.put("/include/gym_header.jsp", Long.valueOf(1702437700000L));
    _jspx_dependants.put("/common/bootstrap_common.jsp", Long.valueOf(1701407588000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.util.BSPageBar");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("	\n");
      out.write("    ");
 
    	List<Map<String, Object>> bList = (List)request.getAttribute("bList");
    	int size = 0; // 총 레코드 수
    	if(bList != null){
    		size = bList.size();
    	}
    	//out.print(bList);
    	// 26개 일 때
    	// 1 2 3 >  < 4 5 6 
    	
    	// 한 페이지에 몇개씩 뿌릴거야??
    	int numPerPage = 3;
    	int nowPage = 0;
    	if(request.getParameter("nowPage") != null) {
    		nowPage = Integer.parseInt(request.getParameter("nowPage"));
    	}
    
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>게시판{webapp}</title>\n");
      out.write("<!-- \n");
      out.write("	인클루드\n");
      out.write("	1) 액션태그 방식 - a_jsp.java, b_jsp.java -> 이렇게 2개로 나뉘어짐\n");
      out.write("	: 파일이 2개로 생성되고 처리 결과가 a.jsp에 반영됨. 제어권은 a.jsp에게 있다.\n");
      out.write("	: url주소가 바뀌지 않는다. 그러나 b의 내용이 들어와 있다. 순서가 다르다.\n");
      out.write("	2) include directive 방식 -> a.jsp.java -> jps파일은 2개인데 서블릿은 한개이다.\n");
      out.write("	역할\n");
      out.write("	: 인증에 관련된 코드는 서비스 개시 거의 직전에 추가함\n");
      out.write("	: 보통 보안과 관련된 업체는 별도로 선정하고 요구사항을 수렴하는 시스템 이어야 함\n");
      out.write(" -->\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\"> \r\n");
      out.write("<script src=\"	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/board.css\">\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	const boardList = () => {\n");
      out.write("		location.href=\"/board/boardList.gd2\"\n");
      out.write("	}\n");
      out.write("	const searchEnter = (event) => {\n");
      out.write("		console.log('searchEnter')\n");
      out.write("		console.log(window.event.keyCode);\n");
      out.write("		if(window.event.keyCode == 13) {\n");
      out.write("		boardSearch(); // 재사용성			\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	const boardSearch = () => {\n");
      out.write("		console.log('boardSearch');\n");
      out.write("		const gubun = document.querySelector(\"#gubun\").value;\n");
      out.write("		const keyword = document.querySelector(\"#keyword\").value;\n");
      out.write("		console.log(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gubun}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\n");
      out.write("		location.href=\"/board/boardList.gd2?gubun=\"+gubun+\"&keyword=\"+keyword;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	const boardInsert = () => {\n");
      out.write("		// <input type=text name = b_title />\n");
      out.write("		// <input type=text name = b_content />\n");
      out.write("		// <input type=text name = b_writer />\n");
      out.write("		// Enumeration<String> em = req.getParameterNames();\n");
      out.write("		document.querySelector(\"#f_board\").submit(); // form태그에 묶인 컴포넌트 값들이 전송된다.\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	const fileDown = (b_file) => {// b_file=avatar24.png\n");
      out.write("		location.href=\"downLoad.jsp?b_file=\"+b_file;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- header start -->\n");
      out.write("	");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm bg-light navbar-light\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"\">여기내GYM</a>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">로그인</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("        <!-- \r\n");
      out.write("        확장자가 jsp이면 서블릿을 경유하지 않는다. - 목록에 보여줄 데이터가 없다?\r\n");
      out.write("        조회버튼 -> /notice/noticeList.gd요청하자 -  오라클 서버를 경유함\r\n");
      out.write("        확장자가 .gd이면 오라클 서버를 경유하니까 조회결과를 쥐고 있다.\r\n");
      out.write("        쥔다 - request.setAttribute() - 화면 출력하기\r\n");
      out.write("         -->\r\n");
      out.write("          <a class=\"nav-link active\" href=\"/notice/noticeList.gd\">공지사항</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("           <a class=\"nav-link\" href=\"/board/boardList.jsp\">게시판</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">회원관리</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">QnA게시판</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\n");
      out.write("	<!-- header end    -->\n");
      out.write("	<!-- body start    -->\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"page-header\">\n");
      out.write("			<h2>\n");
      out.write("				게시판 <small>게시글목록</small>\n");
      out.write("			</h2>\n");
      out.write("			<hr />\n");
      out.write("		</div>\n");
      out.write("		<!-- 검색기 시작 -->\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-3\">\n");
      out.write("				<select id=\"gubun\" class=\"form-select\" aria-label=\"분류선택\">\n");
      out.write("					<option value=\"none\">분류선택</option>\n");
      out.write("					<option value=\"b_title\">제목</option>\n");
      out.write("					<option value=\"b_writer\">작성자</option>\n");
      out.write("					<option value=\"b_content\">내용</option>\n");
      out.write("				</select>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-6\">\n");
      out.write("				<input type=\"text\" id=\"keyword\" class=\"form-control\"\n");
      out.write("					placeholder=\"검색어를 입력하세요\" aria-label=\"검색어를 입력하세요\"\n");
      out.write("					aria-describedby=\"btn_search\" onkeyup=\"searchEnter()\" />\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-3\">\n");
      out.write("				<button id=\"btn_search\" class=\"btn btn-danger\"\n");
      out.write("					onclick=\"boardSearch()\">검색</button>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- 검색기 끝 -->\n");
      out.write("\n");
      out.write("		<!-- 회원목록 시작 -->\n");
      out.write("		<div class='board-list'>\n");
      out.write("			<table class=\"table table-hover\">\n");
      out.write("				<thead>\n");
      out.write("					<tr>\n");
      out.write("						<th width=\"10%\">#</th>\n");
      out.write("						<th width=\"40%\">제목</th>\n");
      out.write("						<th width=\"20%\">첨부파일</th>\n");
      out.write("						<th width=\"15%\">작성자</th>\n");
      out.write("						<th width=\"15%\">조회수</th>\n");
      out.write("					</tr>\n");
      out.write("				</thead>\n");
      out.write("				<tbody>\n");
      out.write("				");

//				for(int i=0;i<size;i++){
				for(int i=nowPage*numPerPage;i<(nowPage*numPerPage)+numPerPage;i++){
					if(size == i) break;
					Map<String,Object> rmap = bList.get(i);
				
      out.write("					\n");
      out.write("					<tr>\n");
      out.write("						<td>");
      out.print(rmap.get("B_NO") );
      out.write("</td>\n");
      out.write("						<td>");
      out.print(rmap.get("B_TITLE") );
      out.write("</td>\n");
      out.write("						<td>\n");
      out.write("						<!-- 자바스크립트 에서는 값 앞뒤에 싱글 또는 더블 쿼테이션을 붙이지 않으면 변수취급을 한다. -->\n");
      out.write("						<a href=\"javascript:fileDown('");
      out.print( rmap.get("B_FILE") );
      out.write("')\">");
      out.print(rmap.get("B_FILE") );
      out.write("</a> \n");
      out.write("						</td>\n");
      out.write("						<td>");
      out.print(rmap.get("B_WRITER") );
      out.write("</td>\n");
      out.write("						<td>");
      out.print(rmap.get("B_HIT") );
      out.write("</td>\n");
      out.write("					</tr>					\n");
      out.write("					");

					}
					
      out.write("\n");
      out.write("				</tbody>\n");
      out.write("			</table>\n");
      out.write("			<hr />\n");
      out.write("			<!-- [[ Bootstrap 페이징 처리  구간  ]] -->\n");
      out.write("			<div style=\"display: flex; justify-content: center;\">\n");
      out.write("				<ul class=\"pagination\">\n");
      out.write("				");

					String pagePath = "boardList.gd2";
					BSPageBar bspb = new BSPageBar(numPerPage, size, nowPage, pagePath);
					out.print(bspb.getPageBar());
				
      out.write("\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<!-- [[ Bootstrap 페이징 처리  구간  ]] -->\n");
      out.write("			<div class='board-footer'>\n");
      out.write("				<button class=\"btn btn-warning\" onclick=\"boardList()\">전체조회\n");
      out.write("				</button>\n");
      out.write("				&nbsp;\n");
      out.write("				<button type=\"button\" class=\"btn btn-success\" data-bs-toggle=\"modal\"\n");
      out.write("					data-bs-target=\"#boardForm\">글쓰기</button>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- 회원목록   끝  -->\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<!-- body end       -->\n");
      out.write("	<!-- footer start -->\n");
      out.write("	");
      out.write("\r\n");
      out.write(" <div class=\"navbar navbar-expand-sm bg-dark justify-content-center\">\r\n");
      out.write("    <a class=\"navbar-brand\"  style=\"color:white\"  href=\"#\">여기내GYM Copyright &copy; 2023</a>\r\n");
      out.write(" </div>");
      out.write("\n");
      out.write("	\n");
      out.write("		<!-- ========================== [[ 게시판 Modal ]] ========================== -->\n");
      out.write("	<div class=\"modal\" id=\"boardForm\">\n");
      out.write("	  <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("	    <div class=\"modal-content\">\n");
      out.write("	\n");
      out.write("	      <!-- Modal Header -->\n");
      out.write("	      <div class=\"modal-header\">\n");
      out.write("	        <h4 class=\"modal-title\">게시판</h4>\n");
      out.write("	        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("	      </div>\n");
      out.write("	      <!-- Modal body -->\n");
      out.write("	      <div class=\"modal-body\">\n");
      out.write("	      	<!-- <form id=\"f_board\" method=\"get\" action=\"./boardInsert.pj2\"> -->\n");
      out.write("	      	<form id=\"f_board\" method=\"post\" enctype=\"multipart/form-data\" action=\"./boardInsert.gd2\">\n");
      out.write("	      	  <input type=\"hidden\" name=\"method\" value=\"boardInsert\">\n");
      out.write("	          <div class=\"form-floating mb-3 mt-3\">\n");
      out.write("	            <input type=\"text\"  class=\"form-control\" id=\"b_title\" name=\"b_title\" placeholder=\"Enter 제목\" />\n");
      out.write("	            <label for=\"b_title\">제목</label>\n");
      out.write("	          </div>	      	\n");
      out.write("	          <div class=\"form-floating mb-3 mt-3\">\n");
      out.write("	            <input type=\"text\"  class=\"form-control\" id=\"b_writer\" name=\"b_writer\" placeholder=\"Enter 작성자\" />\n");
      out.write("	            <label for=\"b_writer\">작성자</label>\n");
      out.write("	          </div>	      	\n");
      out.write("	          <div class=\"form-floating mb-3 mt-3\">\n");
      out.write("	            <textarea rows=\"5\" class=\"form-control h-25\" aria-label=\"With textarea\" id=\"b_content\" name=\"b_content\"></textarea>\n");
      out.write("			  </div>\n");
      out.write("			  <!-- ============================ 첨부파일 처리 구간 ============================ -->\n");
      out.write("		      <div class=\"input-group mb-3\">\n");
      out.write("				  <input type=\"file\" class=\"form-control\" id=\"b_file\" name=\"b_file\">\n");
      out.write("				  <label class=\"input-group-text\" for=\"b_file\">Upload</label>\n");
      out.write("			  </div>   \n");
      out.write("			  <!-- ============================ 첨부파일 처리 구간 ============================ -->   	\n");
      out.write("	      	</form>\n");
      out.write("	      </div>	\n");
      out.write("	      <div class=\"modal-footer\">\n");
      out.write("	        <input type=\"button\" class=\"btn btn-warning\" data-bs-dismiss=\"modal\" onclick=\"boardInsert()\"  value=\"저장\">\n");
      out.write("	        <input type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\" value=\"닫기\">\n");
      out.write("	      </div>\n");
      out.write("	\n");
      out.write("	    </div>\n");
      out.write("	  </div>\n");
      out.write("	</div>\n");
      out.write("    <!-- ========================== [[ 게시판 Modal ]] ========================== -->\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
